# ┌───────────────────────────────────────────────────────────────────┐
# │                                                                   │
# │                          IMPORTANT NOTE                           │
# │                                                                   │
# │   This file is synced with https://github.com/atomicgo/template   │
# │                                                                   │
# │        Please apply all changes to the template repository        │
# │                                                                   │
# └───────────────────────────────────────────────────────────────────┘

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
